run:
	python train_cnnblstm_with_adabn.py
	python train_transfer_cnnblstm_with_adabn.py

clean_all:
	make clean
	rm -rf ./transfer_params_*
	rm -rf ./params_*
	rm -rf *.out

clean:
	rm -rf ./__pycache__

