#!/bin/sh
# vertical
rm -rf ./transfer_params_100_un_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 0 100 ./params ./transfer_params_100_un_vertical false false false
rm -rf ./transfer_params_10_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 10 0 ./params ./transfer_params_10_semi_vertical false false false
rm -rf ./transfer_params_20_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 20 0 ./params ./transfer_params_20_semi_vertical false false false
rm -rf ./transfer_params_30_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 30 0 ./params ./transfer_params_30_semi_vertical false false false
rm -rf ./transfer_params_50_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 50 0 ./params ./transfer_params_50_semi_vertical false false false
rm -rf ./transfer_params_100_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 100 0 ./params ./transfer_params_100_semi_vertical false false false
# vertical
rm -rf ./transfer_params_100_un_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 0 100 ./params ./transfer_params_100_un_vertical false false false
rm -rf ./transfer_params_10_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 10 0 ./params ./transfer_params_10_semi_vertical false false false
rm -rf ./transfer_params_20_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 20 0 ./params ./transfer_params_20_semi_vertical false false false
rm -rf ./transfer_params_30_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 30 0 ./params ./transfer_params_30_semi_vertical false false false
rm -rf ./transfer_params_50_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 50 0 ./params ./transfer_params_50_semi_vertical false false false
rm -rf ./transfer_params_100_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 100 0 ./params ./transfer_params_100_semi_vertical false false false
# vertical
rm -rf ./transfer_params_100_un_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 0 100 ./params ./transfer_params_100_un_vertical false false false
rm -rf ./transfer_params_10_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 10 0 ./params ./transfer_params_10_semi_vertical false false false
rm -rf ./transfer_params_20_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 20 0 ./params ./transfer_params_20_semi_vertical false false false
rm -rf ./transfer_params_30_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 30 0 ./params ./transfer_params_30_semi_vertical false false false
rm -rf ./transfer_params_50_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 50 0 ./params ./transfer_params_50_semi_vertical false false false
rm -rf ./transfer_params_100_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 100 0 ./params ./transfer_params_100_semi_vertical false false false
# vertical
rm -rf ./transfer_params_100_un_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 0 100 ./params ./transfer_params_100_un_vertical false false false
rm -rf ./transfer_params_10_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 10 0 ./params ./transfer_params_10_semi_vertical false false false
rm -rf ./transfer_params_20_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 20 0 ./params ./transfer_params_20_semi_vertical false false false
rm -rf ./transfer_params_30_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 30 0 ./params ./transfer_params_30_semi_vertical false false false
rm -rf ./transfer_params_50_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 50 0 ./params ./transfer_params_50_semi_vertical false false false
rm -rf ./transfer_params_100_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 100 0 ./params ./transfer_params_100_semi_vertical false false false
# vertical
rm -rf ./transfer_params_100_un_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 0 100 ./params ./transfer_params_100_un_vertical false false false
rm -rf ./transfer_params_10_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 10 0 ./params ./transfer_params_10_semi_vertical false false false
rm -rf ./transfer_params_20_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 20 0 ./params ./transfer_params_20_semi_vertical false false false
rm -rf ./transfer_params_30_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 30 0 ./params ./transfer_params_30_semi_vertical false false false
rm -rf ./transfer_params_50_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 50 0 ./params ./transfer_params_50_semi_vertical false false false
rm -rf ./transfer_params_100_semi_vertical
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/vertical/ 100 0 ./params ./transfer_params_100_semi_vertical false false false
