#!/bin/sh
# multiuser
rm -rf ./transfer_params_100_un_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 0 100 ./params ./transfer_params_100_un_multiuser false false false
rm -rf ./transfer_params_10_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 10 0 ./params ./transfer_params_10_semi_multiuser false false false
rm -rf ./transfer_params_20_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 20 0 ./params ./transfer_params_20_semi_multiuser false false false
rm -rf ./transfer_params_30_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 30 0 ./params ./transfer_params_30_semi_multiuser false false false
rm -rf ./transfer_params_50_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 50 0 ./params ./transfer_params_50_semi_multiuser false false false
rm -rf ./transfer_params_100_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 100 0 ./params ./transfer_params_100_semi_multiuser false false false
# multiuser
rm -rf ./transfer_params_100_un_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 0 100 ./params ./transfer_params_100_un_multiuser false false false
rm -rf ./transfer_params_10_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 10 0 ./params ./transfer_params_10_semi_multiuser false false false
rm -rf ./transfer_params_20_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 20 0 ./params ./transfer_params_20_semi_multiuser false false false
rm -rf ./transfer_params_30_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 30 0 ./params ./transfer_params_30_semi_multiuser false false false
rm -rf ./transfer_params_50_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 50 0 ./params ./transfer_params_50_semi_multiuser false false false
rm -rf ./transfer_params_100_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 100 0 ./params ./transfer_params_100_semi_multiuser false false false
# multiuser
rm -rf ./transfer_params_100_un_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 0 100 ./params ./transfer_params_100_un_multiuser false false false
rm -rf ./transfer_params_10_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 10 0 ./params ./transfer_params_10_semi_multiuser false false false
rm -rf ./transfer_params_20_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 20 0 ./params ./transfer_params_20_semi_multiuser false false false
rm -rf ./transfer_params_30_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 30 0 ./params ./transfer_params_30_semi_multiuser false false false
rm -rf ./transfer_params_50_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 50 0 ./params ./transfer_params_50_semi_multiuser false false false
rm -rf ./transfer_params_100_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 100 0 ./params ./transfer_params_100_semi_multiuser false false false
# multiuser
rm -rf ./transfer_params_100_un_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 0 100 ./params ./transfer_params_100_un_multiuser false false false
rm -rf ./transfer_params_10_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 10 0 ./params ./transfer_params_10_semi_multiuser false false false
rm -rf ./transfer_params_20_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 20 0 ./params ./transfer_params_20_semi_multiuser false false false
rm -rf ./transfer_params_30_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 30 0 ./params ./transfer_params_30_semi_multiuser false false false
rm -rf ./transfer_params_50_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 50 0 ./params ./transfer_params_50_semi_multiuser false false false
rm -rf ./transfer_params_100_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 100 0 ./params ./transfer_params_100_semi_multiuser false false false
# multiuser
rm -rf ./transfer_params_100_un_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 0 100 ./params ./transfer_params_100_un_multiuser false false false
rm -rf ./transfer_params_10_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 10 0 ./params ./transfer_params_10_semi_multiuser false false false
rm -rf ./transfer_params_20_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 20 0 ./params ./transfer_params_20_semi_multiuser false false false
rm -rf ./transfer_params_30_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 30 0 ./params ./transfer_params_30_semi_multiuser false false false
rm -rf ./transfer_params_50_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 50 0 ./params ./transfer_params_50_semi_multiuser false false false
rm -rf ./transfer_params_100_semi_multiuser
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/multiuser/ 100 0 ./params ./transfer_params_100_semi_multiuser false false false
