#!/bin/sh
# horizon
rm -rf ./transfer_params_100_un_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 0 100 ./params ./transfer_params_100_un_horizon false false false
rm -rf ./transfer_params_10_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 10 0 ./params ./transfer_params_10_semi_horizon false false false
rm -rf ./transfer_params_20_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 20 0 ./params ./transfer_params_20_semi_horizon false false false
rm -rf ./transfer_params_30_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 30 0 ./params ./transfer_params_30_semi_horizon false false false
rm -rf ./transfer_params_50_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 50 0 ./params ./transfer_params_50_semi_horizon false false false
rm -rf ./transfer_params_100_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 100 0 ./params ./transfer_params_100_semi_horizon false false false
# horizon
rm -rf ./transfer_params_100_un_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 0 100 ./params ./transfer_params_100_un_horizon false false false
rm -rf ./transfer_params_10_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 10 0 ./params ./transfer_params_10_semi_horizon false false false
rm -rf ./transfer_params_20_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 20 0 ./params ./transfer_params_20_semi_horizon false false false
rm -rf ./transfer_params_30_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 30 0 ./params ./transfer_params_30_semi_horizon false false false
rm -rf ./transfer_params_50_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 50 0 ./params ./transfer_params_50_semi_horizon false false false
rm -rf ./transfer_params_100_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 100 0 ./params ./transfer_params_100_semi_horizon false false false
# horizon
rm -rf ./transfer_params_100_un_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 0 100 ./params ./transfer_params_100_un_horizon false false false
rm -rf ./transfer_params_10_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 10 0 ./params ./transfer_params_10_semi_horizon false false false
rm -rf ./transfer_params_20_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 20 0 ./params ./transfer_params_20_semi_horizon false false false
rm -rf ./transfer_params_30_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 30 0 ./params ./transfer_params_30_semi_horizon false false false
rm -rf ./transfer_params_50_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 50 0 ./params ./transfer_params_50_semi_horizon false false false
rm -rf ./transfer_params_100_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 100 0 ./params ./transfer_params_100_semi_horizon false false false
# horizon
rm -rf ./transfer_params_100_un_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 0 100 ./params ./transfer_params_100_un_horizon false false false
rm -rf ./transfer_params_10_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 10 0 ./params ./transfer_params_10_semi_horizon false false false
rm -rf ./transfer_params_20_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 20 0 ./params ./transfer_params_20_semi_horizon false false false
rm -rf ./transfer_params_30_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 30 0 ./params ./transfer_params_30_semi_horizon false false false
rm -rf ./transfer_params_50_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 50 0 ./params ./transfer_params_50_semi_horizon false false false
rm -rf ./transfer_params_100_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 100 0 ./params ./transfer_params_100_semi_horizon false false false
# horizon
rm -rf ./transfer_params_100_un_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 0 100 ./params ./transfer_params_100_un_horizon false false false
rm -rf ./transfer_params_10_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 10 0 ./params ./transfer_params_10_semi_horizon false false false
rm -rf ./transfer_params_20_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 20 0 ./params ./transfer_params_20_semi_horizon false false false
rm -rf ./transfer_params_30_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 30 0 ./params ./transfer_params_30_semi_horizon false false false
rm -rf ./transfer_params_50_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 50 0 ./params ./transfer_params_50_semi_horizon false false false
rm -rf ./transfer_params_100_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 100 0 ./params ./transfer_params_100_semi_horizon false false false
# horizon
rm -rf ./transfer_params_100_un_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 0 100 ./params ./transfer_params_100_un_horizon false false false
rm -rf ./transfer_params_10_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 10 0 ./params ./transfer_params_10_semi_horizon false false false
rm -rf ./transfer_params_20_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 20 0 ./params ./transfer_params_20_semi_horizon false false false
rm -rf ./transfer_params_30_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 30 0 ./params ./transfer_params_30_semi_horizon false false false
rm -rf ./transfer_params_50_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 50 0 ./params ./transfer_params_50_semi_horizon false false false
rm -rf ./transfer_params_100_semi_horizon
python train_transfer_cnnblstm_with_adabn.py ../dataset/all_transfer/horizon/ 100 0 ./params ./transfer_params_100_semi_horizon false false false
